### ISSUE TITLE
Server Crashes when directly inputting items from machines

### ISSUE THREAD

**Issue by KroniQPlayer** [OfekN-mods/emc-interface#5]
could you please add support for thermal and create as have had 2 different crashes, related to items being pumped into the emcinterface via direct input from thermal pulverizer and create chutes.
[crash-2024-06-12_16.47.36-server.txt](https://github.com/user-attachments/files/15808534/crash-2024-06-12_16.47.36-server.txt)
[crash-2024-06-11_15.07.34-server.txt](https://github.com/user-attachments/files/15808542/crash-2024-06-11_15.07.34-server.txt)

Minecraft version 1.20.1
Forge Version 47.2.30

**Comment by ofek2608** [comment]
Thanks for the bug report
I can't reproduce this bug.
Can you please specify steps to reproduce?
Are you playing on a server or on a single player world?

**Comment by KroniQPlayer** [comment]
hmm wierd you cant reproduce. 

maybe its just a freak thing.

we are actively developing a modpack on a server

one player had his emc generation done through create processing and then being dropped through chutes into the emc interface from the top,

the other player was processing with thermal machine ( not too sure which one ) and auto outputting directly into the emc interface.

**Comment by KroniQPlayer** [comment]
new crash this morning involving AE2 now
seems to happen when affected player dies in the end, and then continually crashes after they login until we remove thier emc interfaces, we have disabled the mod for now,  until this crash can be figured out.

[crash-2024-06-13_12.45.56-server.txt](https://github.com/user-attachments/files/15820701/crash-2024-06-13_12.45.56-server.txt)

**Comment by Jumpy85Plays** [comment]
> new crash this morning involving AE2 now seems to happen when affected player dies in the end, and then continually crashes after they login until we remove thier emc interfaces, we have disabled the mod for now, until this crash can be figured out.
> 
> [crash-2024-06-13_12.45.56-server.txt](https://github.com/user-attachments/files/15820701/crash-2024-06-13_12.45.56-server.txt)

Considering this new info and having confirmed this on an actual server and not just a Essential/MineTogether one. Yes it does cause crashing whenever the person who placed down the EMC Interface dies

**Comment by ofek2608** [comment]
Seems like it's a bug in ProjectE's API but I can at least stop this crash from happening.
I fixed it with version 1.20.1.1
